spring:
  application:
    name: infra
  config:
    import: optional:classpath:env/.env[.properties]
  profiles:
    active: local

aws:
  s3:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: ${S3_BUCKET_NAME}
    baseUrl: ${S3_BASE_URL}

discord:
  webhook:
    signup: null
    withdraw: null
    daily-report: null
    nplusone-occurrence: null

---
spring:
  config:
    activate:
      on-profile: local

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectUri: ${KAKAO_LOCAL_REDIRECT_URI}
  clientSecret: ${KAKAO_CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: dev

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectUri: ${KAKAO_DEV_REDIRECT_URI}
  clientSecret: ${KAKAO_CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: prod

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectUri: ${KAKAO_PROD_REDIRECT_URI}
  clientSecret: ${KAKAO_CLIENT_SECRET}

discord:
  webhook:
    signup: ${SIGNUP_DISCORD_WEBHOOK_URL}
    withdraw: ${WITHDRAW_DISCORD_WEBHOOK_URL}
    daily-report: ${DAILY_REPORT_DISCORD_WEBHOOK_URL}
    nplusone-occurrence: ${DISCORD_WEBHOOK_NPLUSONE_OCCURRENCE_URL}
