spring:
  application:
    name: api
  profiles:
    active: local
  config:
    import:
      - domain.yml
      - infra.yml
      - common.yml

  security:
    user:
      name: user
      password: 1234

  jwt:
    token:
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

swagger:
  user: ${SWAGGER_USER}
  password: ${SWAGGER_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

